<a href="https://colab.research.google.com/github/NicoleParedes24/Taller-Numpy/blob/main/actividades_modulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TALLER NUMPY

***Autor:*** Nicole Paredes

***Fecha:*** 16/04/2026

##MODULO 1

###Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension

In [2]:
multiplos7=[x for x in range(1,101) if x % 7==0]
print(multiplos7)


[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


###Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}

In [3]:
datos={'a':10,'b':25,'c':7,'d':18}


a) Crea una lista con las claves cuyo valor sea mayor a 12.


In [4]:
mayores = [k for k, v in datos.items() if v > 12]
print(mayores)

['b', 'd']


b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado.

In [ ]:
diccionario= {k: v**2 for k, v in datos.items() if v > 12}
print(diccionario)

{'b': 625, 'd': 324}


###Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con: longitud, suma, promedio, mínimo y máximo de la lista.


In [6]:

def resumen(lista):
    return {
        'longitud': len(lista),
        'suma ': sum(lista),
        'promedio': sum(lista) / len(lista) if lista else 0,
        'minimo': min(lista) if lista else None,
        'maximo': max(lista) if lista else None
    }


In [ ]:

print(resumen([1, 2, 3, 4, 3]))

{'longitud': 5, 'suma': 13, 'promedio': 2.6, 'minimo': 1, 'maximo': 4}


###Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5]

In [ ]:
def potencia(x, n):
    return x ** n

lista=[1,2,3,4,5]




In [ ]:
res=list(map(lambda x: potencia(x, 3), lista))
print(res)

[1, 8, 27, 64, 125]


##MODULO 2


###Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):


a) Vector con enteros del 1 al 20.


In [ ]:
import numpy as np
#arrange (inicio, hasta -1)
v=np.arange(1,21)
print(v)
#Dimension del arreglo
print("SHAPE: ", v.shape)
#tipo de datos DTYPE Todos los numeros son enteros de 64 bits
print("DYTPE: ",v.dtype)
#Cuantas dimensiones tiene un arreglo
print("NDIM: ",v.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
SHAPE:  (20,)
DYTPE:  int64
NDIM:  1


b) Matriz de ceros de 5 filas y 3 columnas.


In [ ]:
import numpy as np
#matriz de ceros 5x3
matriz=np.zeros((5,3))

print(matriz)
print("SHAPE: ",matriz.shape)
print("DTYPE:", matriz.dtype)
print("NDIM: ",matriz.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
SHAPE:  (5, 3)
DTYPE: float64
NDIM:  2


c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
import numpy as np
#iniciio, fin,puntos
a=np.linspace(-1,1,10)
print(a)
print("SHAPE: ",a.shape)
print("DTYPE:", a.dtype)
print("NDIM: ",a.ndim)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


###Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.


Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].


In [ ]:
import numpy as np

#semilla fija 99
np.random.seed(99)
#valores entre 0 y 50
#de donde hasta donde y el tamaño del vector
a=np.random.randint(0,51, size=(4,4))
print(a)
print("SHAPE: ",a.shape)
print("DTYPE:", a.dtype)

print("NBYTES:", a.nbytes)
print("NDIM: ",a.ndim)


print("Elementos 2,3 :", a[2,3])



[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
SHAPE:  (4, 4)
DTYPE: int64
NBYTES: 128
NDIM:  2
Elementos 2,3 : 49


###Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código.


In [ ]:
import numpy as np
a =np.array([1,2,3])
#son numneros flotantes python lo detecta
b= np.array([1.0,2.0,3.0])

print(a)
print(b)


[1 2 3]
[1. 2. 3.]


###Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace())

In [ ]:
import numpy as np
#matriz identidad
mi= np.eye(5)
print(mi)

suma=np.trace(mi)
print("suma diagonal:" ,suma)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
suma diagonal: 5.0


##MODULO 3



###Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)


In [ ]:
import numpy as np

A=np.arange(1,26).reshape(5,5)
print(A)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.


In [ ]:
sub=A[2:,:3]
print(sub)

[[11 12 13]
 [16 17 18]
 [21 22 23]]


b) Extrae la segunda columna completa.


In [ ]:
col=A[0:,1]
print(col)

[ 2  7 12 17 22]


c) Extrae los elementos de los ángulos (esquinas) de la matriz.


In [ ]:
print(A)

tam=len(A)-1
arribaIzq=A[0,0]
arribaDer=A[0,tam]
abajoIzq=A[tam,0]
abajoDer=A[tam,tam]

print("Superior Izquierda: ",arribaIzq )
print("Superior Derecha: ",arribaDer )


print("Inferior Izquierda: ",abajoIzq )

print("Inferior Derecha: ",abajoDer )


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Superior Derecha:  5
Superior Izquierda:  1
Inferior Derecha:  25
Inferior Izquierda:  21


###Ejercicio 2: Con la misma matriz A:


a) Crea una máscara booleana para los valores mayores a 12.

In [ ]:
mascara=A>12
print(mascara)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


b) Reemplaza esos valores por -1 en una copia del array

In [ ]:

# np.where(cond, valor_si_True, valor_si_False)
copia_A=A.copy()
copia_A=np.where(copia_A>12,-1,copia_A)
print(copia_A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


c) Usa np.where para reemplazar impares por 0 y mantener los pares.


In [ ]:
import numpy as np

copia_b=A.copy()
copia_b=np.where(copia_b%2==1, 0,copia_b)
print(copia_b)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


###Ejercicio 3: Crea un vector de 24 elementos con arange(24)

In [9]:
import numpy as np

v=np.arange(24)
print(v)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Reorganízalo en: (a) matriz 6×4


In [10]:
matriz=v.reshape(6,4)
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


(b) tensor 2×3×4

In [11]:
matriz2=v.reshape(2,3,4)
print(matriz2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(c) vector fila 1×24.

In [12]:
vector=v.reshape(1,24)
print(vector)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


###Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento en un slice y verifica que el array original también cambia.


In [13]:
v = np.arange(12)

M = v.reshape(3, 4)
#es la copia -flatten
flat = M.flatten()
#es la vista
rav = M.ravel()
flat[0] = 999
# flatten no modifica el original->0
print(M[0, 0])
rav[0] = 777
# 777 -> ravel(vista) si lo modifica
print(M[0, 0])



0
777


##MODULO 4


###Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7)

In [14]:
import numpy as np

np.random.seed(7)
enteros=np.random.randint(1,101,(5,4))
print(enteros)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]


a) Calcula la media, máximo y mínimo de cada columna.

In [15]:
media=enteros.mean(axis=0)
minimo=enteros.min(axis=0)
maximo=enteros.max(axis=0)

print("Media: ", media)

print("Maximo: ", maximo)

print("Minomo: ", minimo)


Media:  [51.8 51.4 41.8 60.2]
Maximo:  [84 91 93 90]
Minomo:  [15 24  8 40]


b) Calcula la suma acumulada de la primera fila

In [ ]:
print(enteros)

sumaAcumulada=np.sum(enteros[0])
print("Suma primera fila: ",sumaAcumulada)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]
Suma primera fila:  211


c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
##Fórmula: (x - min_col) / (max_col - min_col)

In [16]:
#columna axis=0
min=np.min(enteros,axis=0)
max=np.max(enteros,axis=0)
formula=(enteros-min)/(max-min)
print(formula)



[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


###Ejercicio 2: Usando broadcasting

a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].

In [ ]:
import numpy as np

vectorFila=np.array([1,2,3,4])
vectorColumna=np.array([[10],[20],[30]])

print("Vector fila: ", vectorFila)


print("Vector columna: \n", vectorColumna)







Vector fila:  [1 2 3 4]
Vector columna: 
 [[10]
 [20]
 [30]]


b) Suma ambos vectores y explica el shape del resultado.

In [ ]:
suma=vectorFila+vectorColumna

print(suma)
print(suma.shape)
 #3,4 La fila se repite 3 veces y la columna 4, se forma una matriz 3x4

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


###Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:

In [ ]:
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])


a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)


In [ ]:
promedio=np.average(notas)
print("PROMEDIO: ",promedio)

notaMayorPromedio=notas>promedio
print(notaMayorPromedio)

print("Estudiantes con nota mayor al promedio: ",np.sum(notaMayorPromedio))

PROMEDIO:  81.5
[False  True  True False  True False]
Estudiantes con nota mayor al promedio:  3


b) Imprime solo los nombres de esos estudiantes

In [ ]:
nombreMascara=nombres[notaMayorPromedio]
print(nombreMascara)

['Ana' 'Diana' 'Eva']



###Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.

In [17]:
m1=np.random.randint(1,9,(3,4))
m2=np.random.randint(9,15,(3,4))
print("matriz 1: \n",m1)

print("matriz 2\n",m2)

#por filas axis=0
concatenar1=np.concatenate([m1,m2],axis=0)
print("Concatenacion verticalmente: \n", concatenar1)

#por columnas axis=1
concatenar2=np.concatenate([m1,m2],axis=1)
print("Concatencacion horizontalmente: \n",concatenar2)

matriz 1: 
 [[1 4 8 3]
 [7 4 5 5]
 [8 6 1 1]]
matriz 2
 [[14  9 12 14]
 [ 9 11  9 10]
 [13 10 12 12]]
Concatenacion verticalmente: 
 [[ 1  4  8  3]
 [ 7  4  5  5]
 [ 8  6  1  1]
 [14  9 12 14]
 [ 9 11  9 10]
 [13 10 12 12]]
Concatencacion horizontalmente: 
 [[ 1  4  8  3 14  9 12 14]
 [ 7  4  5  5  9 11  9 10]
 [ 8  6  1  1 13 10 12 12]]


Luego divide el resultado vertical en 3 partes iguales con vsplit


In [18]:
print(concatenar1)
#divide el concatenar1 en 3
div=np.vsplit(concatenar1,3)
print(div)

[[ 1  4  8  3]
 [ 7  4  5  5]
 [ 8  6  1  1]
 [14  9 12 14]
 [ 9 11  9 10]
 [13 10 12 12]]
[array([[1, 4, 8, 3],
       [7, 4, 5, 5]]), array([[ 8,  6,  1,  1],
       [14,  9, 12, 14]]), array([[ 9, 11,  9, 10],
       [13, 10, 12, 12]])]
