<a href="https://colab.research.google.com/github/NicoleParedes24/Taller-Numpy/blob/main/guia_estudio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller de numpy

*Autor:* **Nicole Paredes**

Fecha: 16/04/2026


##Listas


In [ ]:
numeros=[10,2,0,3,4,5,60]
mixta=[1,'hola',True,3.7]
vacia=[]
de_rango=list(range(1,10))


In [ ]:
# regresa al inicio
print(numeros[0:-6])
print(numeros[0])
print(numeros[len(numeros)-1])


[10]
10
60


##SLICING
##[inicio :fin:paso]

In [ ]:
print(numeros[::-1])
print(numeros[1:4]) #coge desde n a -1
print(numeros[::3])


print(numeros[:3]) # DESDE EL INICO HASTA EL INDICE 2
print(numeros[::2])
print(numeros[::-1])# invertir la lista

print(numeros[1::-1])

[600, 60, 5, 4, 3, 0, 99, 2, 10]
[2, 99, 0]
[10, 0, 5]
[10, 2, 99]
[10, 99, 3, 5, 600]
[600, 60, 5, 4, 3, 0, 99, 2, 10]
[2, 10]


##Metodos principales

In [ ]:
numeros.append(600) #insertat el 600
numeros.insert(2,99) # insertar en la posicion 2 el numero 99
print(numeros)
numeros.remove(99) #elimina solo el primero
numeros
numeros.pop()#elimina el ultimo
print(len(numeros), numeros)

[10, 2, 99, 99, 0, 3, 4, 5, 60, 600, 600, 600, 600, 600, 600, 600, 600]
15 [10, 2, 99, 0, 3, 4, 5, 60, 600, 600, 600, 600, 600, 600, 600]


##List Comprehensions

In [ ]:

#cuadrados = [x**2 for x in numeros]
cuadrados = [x**2 for x in range(1, 8)] # va a ser del 1 a 8-1
print(numeros)
print(cuadrados)


[10, 2, 99, 0, 3, 4, 5, 60, 600, 600, 600, 600, 600, 600, 600]
[1, 4, 9, 16, 25, 36, 49]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


##Con condición

In [ ]:

pares = [x for x in range(1, 21) if x % 2 == 0]
print(pares)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


##Comprehension anidada para generar una matriz
## Tabla de multiplicar 3x3

In [ ]:
tabla = [[i * j for j in range(1, 4)] for i in range(1, 4)]
print(tabla)

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


##Transformaciones de tipo

In [ ]:
palabras=['holA','SI','no']
minusculas=[w.lower() for w in palabras] #aqui recorre todo y hace en minusculas
mayusculas=[l.upper() for l in palabras]
print(palabras)
print(minusculas)
print(mayusculas)

['holA', 'SI', 'no']
['hola', 'si', 'no']
['HOLA', 'SI', 'NO']


##TUPLAS


In [ ]:
coordenada = (3.5, -1.2) # tupla de 2 elementos
dimensiones = (28, 28, 3) # alto, ancho, canales (imagen RGB)
unitaria = (42,) # COMA CREA TUPLA
no_tupla = (42) # LO TOMA COMO ENTERO HAYQ  PONER ,


(3.5, -1.2)
(28, 28, 3)
42 <class 'int'>
(42,)
42 <class 'int'>


##Acceso

In [ ]:

print(coordenada)
print(dimensiones)
print(unitaria[-1],type(no_tupla))
print(unitaria)
print(no_tupla, type(no_tupla))

In [ ]:
##Desempaquetado

In [ ]:
x,y= coordenada # si hay uno mas o menos no va a funcionar
alto,ancho, profundidad= dimensiones
print(x,y,alto,ancho,profundidad)

3.5 -1.2 28 28 3


##DICCIONARIOS


In [ ]:
estudiante ={
    'nombre': 'Nicole',
    'edad': 22,
    'notas':[9.9,10,9],
    'activo': True,
   # 0:'hola',
    'nombre':'nicol'
}

acceso a los diccionarios


In [ ]:
print(estudiante['nombre'])
print('notas',estudiante['notas'])
print(estudiante[0])

print(estudiante.get('carrerra','n/a'))


nicol
notas [9.9, 10, 9]
hola
n/a


##Modificacion


In [ ]:
estudiante['edad'] = 23 # modifica valor existente
estudiante['semestre'] = 6 # agrega nueva clave

In [ ]:
##Iteración

In [ ]:
for clave, valor in estudiante.items():
  print(f'{clave:12s} → {valor}')

nombre       → nicol
edad         → 22
notas        → [9.9, 10, 9]
activo       → True


##Dict Comprehension


In [ ]:
cuadrados = {x: x**3 for x in range(1, 6)} # ESTA SCANDO CUBOS



##Acceso

In [ ]:
for i in cuadrados:
  print(i)
  print()
  print(cuadrados[i])

In [ ]:
# ver SI HAY existencia de la clave
if 'nombre' in estudiante:
  print('La clave existe')

La clave existe


In [ ]:
elementos = list(estudiante.values())
print(elementos,type(elementos))

['nicol', 22, [9.9, 10, 9], True] <class 'list'>


##FUNCIONES

In [ ]:
#funcion basica para el nombre
def saludar(nombre,edad):
  return f'Hola {nombre}, tu edad es,{edad}'

In [ ]:
print(saludar('nicole',20))

Hola,nicole, tu edad es,20


##Funcion con parametros por defecto

In [ ]:
def potencia (base, exponente=2):
  return base ** exponente

In [ ]:
print(potencia(5))
print(potencia(5,3))

25
125


##Retorno multiple, devuelve una tupla

In [ ]:
def min_max(lista):
  return min(lista),max(lista)

In [ ]:
min,max=min_max([2,5,6,7,2,2,3,4,4,55])
print(min,max)

2 55


##Lambda

In [ ]:
doble=lambda x: x*2
#equivale a
def doble2(x):
  return x*2


In [ ]:
print(doble(2))
print(doble2(2))

4
4


##sorted - ordenar

In [10]:
nums=[2,3,4,0,6,7,1,2,3]
#ordenar por cuadrados
ordenador=sorted(nums, key=lambda x:x**2)
orden1=sorted(nums,key=lambda x:x==0)#pone los ceros al final
ordenados = sorted(nums, key=lambda x: -x)#orden descendente
orden2=sorted(nums,key=lambda x:x)#orden ascendente

print(ordenados)
print(orden2)
print(orden1)

print(ordenador)


[7, 6, 4, 3, 3, 2, 2, 1, 0]
[0, 1, 2, 2, 3, 3, 4, 6, 7]
[2, 3, 4, 6, 7, 1, 2, 3, 0]
[0, 1, 2, 2, 3, 3, 4, 6, 7]


##Map y filter

In [14]:
nums2 = [1, 2, 3,4,8,9,9,11,22]
cuadrados = list(map(lambda x: x**2, nums2))
print(cuadrados)
#Es lo mismo
#def cuadrado(x):
#   return x**2

mayores=list(filter( lambda x:x>4, nums2))
print(mayores)

[1, 4, 9, 16, 64, 81, 81, 121, 484]
[8, 9, 9, 11, 22]


##Creación de arrays

##Array 1 (vector)

In [18]:
import numpy as np
v=np.array([10,20,30,40,50])
print(v)
#N-dimensional array es el tipo principal de numpy
print(type(v))
#int 64 = enteros de 64 bits
print(v.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


##Array 2-D (Matriz)

In [19]:
m=np.array([[1,2,3],
            [4,5,6],
            [6,7,8]])
print(m)



[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [29]:
#son enteros
m1=np.arange(1,6)
print(m1)
#decimales
m2=np.linspace(1,4,4)
print(m2)
#sin numpy
m3=list(range(1,20))
print(m3)
#matriz
m4=np.arange(1,7).reshape(2,3)
print(m4)
#numeros random
m5=np.random.randint(2,9,(2,3))
print(m5)

[1 2 3 4 5]
[1. 2. 3. 4.]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[[1 2 3]
 [4 5 6]]
[[2 4 7]
 [5 2 5]]


##Upcasting automatico

In [33]:
#mezcla int + float
mix=np.array([1,2,3,4.4,3,'3',"e"])
print(mix)
print(mix.dtype)

['1' '2' '3' '4.4' '3' '3' 'e']
<U32


##Forzar tipo de dato

In [36]:
#quiero que esto numeros se conviertan a float
float32= np.array([1,2,3], dtype=np.float32)
print(float32)
#cualquier otro numero diferente a 0 imprime true
booleano =np.array([2,1,0],dtype=np.bool)
print(booleano)

[1. 2. 3.]
[ True  True False]


##Arrays de ceros y unos

In [40]:
ceros=np.zeros((2,3))
print(ceros)
print(ceros.shape)
unos=np.ones((2,3))
print(unos)



[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


##Matriz Identidad

In [41]:
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##Arrange vs linespace

In [43]:
#Arrange define el Paso
a=np.arange(0,10,2)# el 10 excluido
print(a)

#linespace: cantidad de puntos
b=np.linspace(2,10,10)
print(b)

[0 2 4 6 8]
[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


##Aleatorios

In [47]:
np.random.seed(42) # semilla fija
uniforme = np.random.rand(3, 4) # valores  0,1
print(uniforme,"\n")
normal = np.random.randn(3, 4) # distribución normal (μ=0, σ=1)
print(normal,"\n")
enteros = np.random.randint(1, 10, size=(3, 3)) # enteros en [1, 10)
print(enteros)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]] 

[[-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]] 

[[3 7 4]
 [9 3 5]
 [3 7 5]]


##Tensor 3D

In [49]:
import numpy as np
#Array de 3 dimensiones- tensor
A = np.random.randint(0, 100, size=(4, 3, 2))

print('shape: ', A.shape)
#numero de dimensiones=3d
print('ndim: ', A.ndim)
#tamaño
print('size: ', A.size)
#tipo de dato de cada num
print('dtype: ', A.dtype)
#cada numero ocupa 8bits
print('itemsize: ', A.itemsize)

shape:  (4, 3, 2)
ndim:  3
size:  24
dtype:  int64
itemsize:  8


##Diferencia entre shape de vector y matriz

In [50]:
v = np.array([1, 2, 3, 4, 5])
M = np.array([[1, 2, 3, 4, 5]])
print(v.shape) # (5,) → vector 1-D con 5 elementos
print(M.shape) # (1, 5) → matriz 2D de 1 fila y 5 columnas



(5,)
(1, 5)


##MODULO 3: INDEXING, SLICING Y TRANSFORMACIONES DE FORMA

In [51]:
M = np.array([[10, 20, 30],
[40, 50, 60],
[70, 80, 90]])


##Acceso a elementos


In [53]:
print(M)
print(M[0, 0])
print(M[1, 2])
#ultimo elemento
print(M[-1, -1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
60
90


##Acceso a filas y columnas completas

In [54]:
# ':' -> 'todos los elementos de ese eje'
print(M[0, :]) # [10 20 30] → fila 0 completa
print(M[:, 1]) # [20 50 80] → columna 1 completa
print(M[-1, :]) # [70 80 90] → última fila

[10 20 30]
[20 50 80]
[70 80 90]


##Tensor 3D

In [58]:
T = np.arange(24).reshape(2, 3, 4) # 2 'páginas', 3 filas, 4 columnas
print(T,"\nfin")

print(T[0]) # primera 'página' (matriz 3×4)
print(T[1, 2, 3]) # página 1, fila 2, columna 3
print(T[:, 0, :]) # primera fila de TODAS las páginas


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
fin
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
23
[[ 0  1  2  3]
 [12 13 14 15]]


##Slicing

In [59]:
import numpy as np
A = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

##Slicing basico

In [68]:
# [fila_ini:fila_fin , col_ini:col_fin]

print(A)

sub=A[0:2,1:3]
print(sub,"\n")

sub2=A[1:3,2:4]
print(sub2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]] 

[[ 7  8]
 [11 12]]


##Omitir indices

In [69]:
print(A[:2, :]) # primeras 2 filas completas
print(A[1:, 2:]) # desde fila 1, desde columna 2


[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


##Con paso

In [72]:
print(A)
print(A[::2, ::2]) # filas pares, columnas pares

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  3]
 [ 9 11]]


##Vista vs copia

In [76]:
vista = A[0, :] # es una vista
copia = A[0, :].copy() # es una copia independiente
print("VISTA\n",vista)
print("COPIA\n",copia,"fin\n")
vista[0] = 999 # modifica A también!
copia[0] = 888 # NO modifica A
print(A[0, :]) # [999 2 3 4] ← vista modificó el original
print(np.shares_memory(A, vista)) # True
print(np.shares_memory(A, copia)) # False

VISTA
 [999   2   3   4]
COPIA
 [999   2   3   4] fin

[999   2   3   4]
True
False


##Máscara booleana

In [77]:
import numpy as np
datos = np.array([[5, 12, 3, 18],
[7, 2, 15, 9],
[11, 6, 20, 1]])

In [79]:
mascara = datos > 10 # array de True/False
print(datos)
print()
print(mascara)


[[ 5 12  3 18]
 [ 7  2 15  9]
 [11  6 20  1]]

[[False  True False  True]
 [False False  True False]
 [ True False  True False]]


##Mascara(filtro)

In [80]:
mayores = datos[mascara] # devuelve 1D con los valores True
print(mayores)


[12 18 15 11 20]


##Combinacion y condiciones

In [81]:
# Valores entre 5 y 15 (inclusive)
rango = datos[(datos >= 5) & (datos <= 15)]
print(rango) # [ 5 12 7 15 9 11 6]

[ 5 12  7 15  9 11  6]


##Modificar elementos con máscara




In [84]:
print(datos)
print()
copia = datos.copy()

copia[copia < 5] = 0 # reemplaza valores menores a 5 con 0
print(copia)

[[ 5 12  3 18]
 [ 7  2 15  9]
 [11  6 20  1]]

[[ 5 12  0 18]
 [ 7  0 15  9]
 [11  6 20  0]]


##Condicional vectorizado

In [87]:
# np.where(cond, valor_si_True, valor_si_False)
print(datos,"\n")
resultado = np.where(datos > 10, datos, 0) # deja >10 reemplaza el resto con 0
print(resultado)

[[ 5 12  3 18]
 [ 7  2 15  9]
 [11  6 20  1]] 

[[ 0 12  0 18]
 [ 0  0 15  0]
 [11  0 20  0]]


##Fancy Indexing

In [88]:
import numpy as np
M = np.array([[10, 11, 12],
[20, 21, 22],
[30, 31, 32],
[40, 41, 42]])

##Seleccion de filas por índice

In [89]:
print(M,"\n")
indices = [0, 2, 3]
print(M[indices]) # filas 0, 2 y 3



[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]] 

[[10 11 12]
 [30 31 32]
 [40 41 42]]


## Selección en orden arbitrario (incluso repetido)

In [91]:

print(M,"\n")

# fila 3, luego 1, luego 3 otra vez, luego 0
print(M[[3, 1, 3, 0]])

[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]] 

[[40 41 42]
 [20 21 22]
 [40 41 42]
 [10 11 12]]


##Combinacion con slicing

In [92]:
print(M,"\n")
# filas 0 y 2, columnas desde la 1
print(M[[0, 2], 1:])


[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]] 

[[11 12]
 [31 32]]


##Fancy indexing de columnas

In [93]:
print(M,"\n")
cols = [2, 0]
print(M[:, cols]) # columnas 2 y 0 (en ese orden)


[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]] 

[[12 10]
 [22 20]
 [32 30]
 [42 40]]


##COPIA - siempre

In [96]:
print(M)
copia = M[[0, 1]]
copia[0, 0] = 999
print("copia\n",copia,"\n")
print(M[0, 0]) # 10 — original no cambia


[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]
copia
 [[999  11  12]
 [ 20  21  22]] 

10


##Reshape — Cambio de Forma

In [99]:
import numpy as np
v = np.arange(12)# del 0 al 11 (n-1)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


##Reshape básico

In [102]:
M2x6 = v.reshape(2, 6) # 2 filas, 6 columnas
print(M2x6,"\n")

M3x4 = v.reshape(3, 4) # 3 filas, 4 columnas
print(M3x4,"\n")
M4x3 = v.reshape(4, 3) # 4 filas, 3 columnas
print(M4x3,"\n")
M2x2x3= v.reshape(2, 2, 3) # tensor 3-D
print(M2x2x3,"\n")


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 



##Uso de -1 (dimension automatica)

In [104]:
print(v,"\n")
# ?x3: NumPy calcula ? = 12/3 = 4 → shape (4,3)
auto = v.reshape(-1, 3)
print(auto.shape) # (4, 3)
auto2 = v.reshape(2, -1) # 2 x ?: ? = 12/2 = 6 → shape (2, 6)
print(auto2.shape) # (2, 6

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

(4, 3)
(2, 6)


##flatten vs ravel

In [106]:
print(v,"\n")
M = v.reshape(3, 4)
flat = M.flatten() # siempre COPIA
print("copia",flat)
rav = M.ravel() # VISTA si es posible
flat[0] = 999
print(M[0, 0]) # 0 → flatten no modifica el original
rav[0] = 777
print(M[0, 0]) # 777 → ravel SÍ modifica el original (es vista)

[777   1   2   3   4   5   6   7   8   9  10  11] 

copia [777   1   2   3   4   5   6   7   8   9  10  11]
777
777


##agregar dimensiones

In [107]:
v1d = np.array([1, 2, 3, 4]) # shape (4,)
col = v1d.reshape(-1, 1) # shape (4, 1) — vector columna
fil = v1d.reshape(1, -1) # shape (1, 4) — vector fila
print(col.shape, fil.shape)

(4, 1) (1, 4)


##MODULO 4: OPERACIONES NUMERICAS Y MANIPULACIÓN DE DATOS

In [108]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

##Operaciones aritmeticas básicas

In [109]:
print("a ",a)
print("b ",b)
print(a + b) # [11 22 33 44 55] suma elemento a elemento
print(b - a) # [ 9 18 27 36 45] resta
print(a * b) # [ 10 40 90 160 250] multiplicación
print(b / a) # [10. 10. 10. 10. 10.] división (devuelve float)
print(a ** 2) # [ 1 4 9 16 25] potencia
print(b // 3) # [ 3 6 10 13 16] división entera
print(b % 3) #  módulo

a  [1 2 3 4 5]
b  [10 20 30 40 50]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[ 3  6 10 13 16]
[1 2 0 1 2]


##Operaciones con escalar( scarlar broadcasting)

In [111]:
print("a ",a)
print("b ",b)
print(a * 3) # [ 3 6 9 12 15]
print(a + 100) # [101 102 103 104 105]
print(a > 2) # [False False True True True]

a  [1 2 3 4 5]
b  [10 20 30 40 50]
[ 3  6  9 12 15]
[101 102 103 104 105]
[False False  True  True  True]


##Matrices

In [113]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
print("M\n",M)
print("N\n",N,"\n")
print(M + N) # [[6,8],[10,12]] — suma elemento a elemento
print(M * N) # [[ 5 12],[21 32]] — producto elemento a elemento
# NOTA: M * N NO es el producto matricial. Para matrices usar M @ N

M
 [[1 2]
 [3 4]]
N
 [[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


##Escalar + vector

In [114]:
v = np.array([1, 2, 3, 4]) # shape (4,)
print("v: ",v)
print(v + 10) # [11 12 13 14] — escalar → (4,)


v:  [1 2 3 4]
[11 12 13 14]


##Vector + matriz

In [118]:
M = np.ones((3, 4)) # shape (3, 4)
print("M\n",M)
v = np.array([10, 20, 30, 40]) # shape (4,) → se convierte a (1,4) → (3,4)
print("v\n",v,"\n")
print(M + v)
# [[11. 21. 31. 41.]
# [11. 21. 31. 41.]
# [11. 21. 31. 41.]]

M
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
v
 [10 20 30 40] 

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


##Columna + fila

In [121]:
 # shape (3, 1)
col = np.array([[1], [2], [3]])
print("col\n",col,"\n")
# shape (4,) → (1, 4)
fil = np.array([10, 20, 30, 40])
print("fil\n",fil,"\n")
# shape (3, 4)
suma = col + fil
print(suma)


col
 [[1]
 [2]
 [3]] 

fil
 [10 20 30 40] 

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


##Normalización por columna

In [124]:
datos = np.random.randint(1, 100, (5, 3))
print("datos: \n",datos,"\n")
maximos = datos.max(axis=0) # shape (3,) — máximo de cada columna

print("maximos:",maximos)
norm = datos / maximos # broadcasting (5,3) / (3,) → (5,3)
print(norm.round(2))

datos: 
 [[73 72 12]
 [34 33 48]
 [23 62 88]
 [37 99 44]
 [86 91 35]] 

maximos: [86 99 88]
[[0.85 0.73 0.14]
 [0.4  0.33 0.55]
 [0.27 0.63 1.  ]
 [0.43 1.   0.5 ]
 [1.   0.92 0.4 ]]


##Funciones universales

In [125]:
import numpy as np
v = np.array([-4.5, -1.0, 0.0, 2.5, 9.0])

##Funciones básicas

In [133]:
print("v:\n ",v,"\n")
print("valor absoluto(abs): ",np.abs(v)) # [4.5 1. 0. 2.5 9. ]
print("\nevita negativos y saca raiz cuadrada:\n",np.sqrt(np.abs(v))) # raíz cuadrada (abs para evitar NaN)
print("\nEleva al cuadrado\n",np.square(v)) # [20.25 1. 0. 6.25 81. ]
print("\nRedondea hacia abajo \n",np.floor(v)) # [-5. -1. 0. 2. 9.] — redondeo hacia abajo
print("\nRedondea hacia arriba\n",np.ceil(v)) # [-4. -1. 0. 3. 9.] — redondeo hacia arrib

v:
  [-4.5 -1.   0.   2.5  9. ] 

valor absoluto(abs):  [4.5 1.  0.  2.5 9. ]

evita negativos y saca raiz cuadrada:
 [2.12132034 1.         0.         1.58113883 3.        ]

Eleva al cuadrado
 [20.25  1.    0.    6.25 81.  ]

Redondea hacia abajo 
 [-5. -1.  0.  2.  9.]

Redondea hacia arriba
 [-4. -1.  0.  3.  9.]


##Exponencial y lograritmo

In [135]:
pos = np.array([1.0, 2.0, 4.0, 8.0])
print("pos: ",pos)
print("\nLN:\n",np.log(pos)) # ln: [0. 0.693 1.386 2.079]
print("\nLog 2:\n",np.log2(pos)) # log₂:[0. 1. 2. 3.]
print("\ne^x:\n",np.exp(pos)) # e^x

pos:  [1. 2. 4. 8.]

LN:
 [0.         0.69314718 1.38629436 2.07944154]

Log 2:
 [0. 1. 2. 3.]

e^x:
 [2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


##Trigonometría (argumentos en radianes)

In [136]:
 # 0, π/2, π, 3π/2, 2π
angulos = np.linspace(0, 2 * np.pi, 5)
print("angulos: ",angulos)
 # [0. 1. 0. -1. -0.]
print(np.sin(angulos).round(4))
# [1. 0. -1. 0. 1.]
print(np.cos(angulos).round(4))

angulos:  [0.         1.57079633 3.14159265 4.71238898 6.28318531]
[ 0.  1.  0. -1. -0.]
[ 1.  0. -1. -0.  1.]


##clip — limitar valores a un rango

In [137]:

datos = np.array([-10, -5, 0, 5, 10, 15, 20])
print(datos)
# valores entre 0 y 10
recortado = np.clip(datos, 0, 10)

# [ 0 0 0 5 10 10 10]
print(recortado)

[-10  -5   0   5  10  15  20]
[ 0  0  0  5 10 10 10]


##maximum / minimum elemento a elemento

In [138]:
a = np.array([3, 1, 7, 2])
b = np.array([4, 5, 2, 8])

print("a: ",a)
print("b: ",b)
print(np.maximum(a, b)) # [4 5 7 8] — máximo entre pares
print(np.minimum(a, b)) # [3 1 2 2] — mínimo entre pares

a:  [3 1 7 2]
b:  [4 5 2 8]
[4 5 7 8]
[3 1 2 2]


##Estadistica y Reducciones

In [139]:
import numpy as np
M = np.array([[4, 7, 2, 8],
[3, 11, 5, 1],
[6, 9, 0, 4]])
# shape:(3, 4)  3 filas, 4 columnas


## Reducción global (todos los ejes)

In [141]:
print(M)
#SUMA TODOS LOS ELEMENTOS#
print(M.sum()) # 60
#Promedio = suma / cantidad
print(M.mean()) # 5.0
#MAS GRANDE
print(M.max()) # 11
#MAS PEQUEÑO
print(M.min()) # 0

[[ 4  7  2  8]
 [ 3 11  5  1]
 [ 6  9  0  4]]
60
5.0
11
0


##Reducción por eje

In [144]:
print("M\n",M,"\n")
#AXIS =0 COLUMNA
#AXIS=1 FILA
print(M.sum(axis=0)) # suma por columna: [13 27 7 13]
print(M.sum(axis=1)) # suma por fila: [21 20 19]
print(M.mean(axis=0)) # media de cada columna
print(M.max(axis=1)) # máximo de cada fila: [8 11 9]

M
 [[ 4  7  2  8]
 [ 3 11  5  1]
 [ 6  9  0  4]] 

[13 27  7 13]
[21 20 19]
[4.33333333 9.         2.33333333 4.33333333]
[ 8 11  9]


##argmin / argmax — índice del extremo

In [146]:
print("índice del mínimo en cada fila: :\n",M.argmin(axis=1))
print("\níndice del máximo en cada columna: \n",M.argmax(axis=0)) # [2 1 1 0]


índice del mínimo en cada fila: :
 [2 3 2]

índice del máximo en cada columna: 
 [2 1 1 0]


##Desviación estándar global y varianza

In [147]:
print("M\n",M,"\n")
print(M.std()) # desviación estándar global
print(M.var(axis=0)) # varianza de cada columna

M
 [[ 4  7  2  8]
 [ 3 11  5  1]
 [ 6  9  0  4]] 

3.1885210782848317
[1.55555556 2.66666667 4.22222222 8.22222222]


## Mantener dimensiones

In [148]:
# shape (1, 4) en vez de (4,)
media = M.mean(axis=0, keepdims=True)
print(media.shape) # (1, 4)
centrado = M - media # broadcasting funciona directamente


(1, 4)


##Suma acumulada

In [ ]:
v = np.array([1, 2, 3, 4, 5])
print(np.cumsum(v)) # [1 3 6 10 15]


##Percentil

In [149]:
print(np.percentile(M, 25)) # percentil 25 (primer cuartil)
print(np.median(M)) # mediana (equivale a percentil 50)


2.75
4.5


##Concatenación y Apilamiento de Arrays

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
[4, 5, 6]])
B = np.array([[7, 8, 9],
[10, 11, 12]])


Concatenacón


In [ ]:
vertical = np.concatenate([A, B], axis=0) # apilar filas
print(vertical.shape) # (4, 3)
horizontal = np.concatenate([A, B], axis=1) # apilar columnas
print(horizontal.shape) # (2, 6

vstack y hstack

In [150]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("v1:", v1)
print("v2:", v2)
#vstack apila hacia abajo
print(np.vstack([v1, v2])) # [[1 2 3], [4 5 6]] → shape (2,3)
#hstack junta a los lados
print(np.hstack([v1, v2])) # [1 2 3 4 5 6] → shape (6,)

v1: [1 2 3]
v2: [4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


stack — crea nuevo eje

In [ ]:
 # shape (2, 2, 3) — nuevo eje al frente
capas = np.stack([A, B], axis=0)
print(capas.shape)

split

In [151]:
import numpy as np

M = np.arange(1, 25).reshape(4, 6)

print("M =")
print(M)
# divide en 2 a lo largo de columnas
partes = np.split(M, 2, axis=1)

print("parte 1 shape:", partes[0].shape)
print("parte 2 shape:", partes[1].shape)

# 4 filas individuales
filas = np.vsplit(M, 4)

# primera fila
print("primera fila:")
print(filas[0])

M =
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
parte 1 shape: (4, 3)
parte 2 shape: (4, 3)
primera fila:
[[1 2 3 4 5 6]]


##Ordenamiento y Búsqueda

In [152]:
import numpy as np
v = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

sort - ordenar

In [154]:
ordenado = np.sort(v) # copia — v no cambia
v.sort() # v ahora está ordenado
print(v)

[1 2 3 4 5 6 7 8 9]


argsort

In [156]:
v = np.array([5, 2, 8, 1, 9, 3])
print("v: ",v)
idx = np.argsort(v) # [3 1 5 0 2 4] — índices que ordenarían v
print(v[idx]) # [1 2 3 5 8 9]


v:  [5 2 8 1 9 3]
[1 2 3 5 8 9]


Reordenar dos arrays en paralelo

In [158]:
import numpy as np
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])

# obtener índices que ordenan las notas de mayor a menor
orden = np.argsort(notas)[::-1]

print("nombres ordenados por nota",nombres[orden])

print("notas ordenadas",notas[orden])

nombres ordenados por nota ['Eva' 'Ana' 'Diana' 'Luis' 'Carlos' 'Pedro']
notas ordenadas [95 92 88 78 75 61]


 np.where con 1 argumento — posiciones de Tru

In [159]:
datos = np.array([0, 5, 0, 3, 0, 8])
print("datos",datos)
pos = np.where(datos > 0) # devuelve tupla de arrays de índices
print(pos) # (array([1, 3, 5]),)
print(datos[pos]) # [5 3 8]

datos [0 5 0 3 0 8]
(array([1, 3, 5]),)
[5 3 8]


unique

In [161]:
colores = np.array([1, 2, 1, 3, 2, 1, 4, 3])
#obtiene valores unicos y cuantas veces se aparece cada uno
unicos, conteos = np.unique(colores, return_counts=True)
#valores unicos
print(unicos) # [1 2 3 4]
#cantidad que aparece cada valor
print(conteos) # [3 2 2 1]

[1 2 3 4]
[3 2 2 1]
